import type { Metadata } from "next";
import { Rubik, Montserrat, MedievalSharp } from "next/font/google";
import "../styles/globals.scss";

const rubik = Rubik({
  variable: "--primary-font-rubik",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const montserrat = Montserrat({
  variable: "--secondary-font-montserrat",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
});

const medievalSharp = MedievalSharp({
  variable: "--tertiary-font-medieval",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${rubik.variable} ${montserrat.variable} ${medievalSharp.variable}`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
